export const SEASON_2026 = {
  year: 2026,
  totalRounds: 22,
  totalDrivers: 22,
  totalTeams: 11,
  completedRounds: 2,
  currentRound: 3,
  nextRace: {
    round: 3,
    name: 'Japanese Grand Prix',
    circuit: 'Suzuka Circuit',
    country: 'Japan',
    flag: '🇯🇵',
    date: 'March 27-29, 2026',
  },
  races: [
    {
      round: 1,
      name: 'Australian Grand Prix',
      circuit: 'Albert Park',
      country: 'Australia',
      flag: '🇦🇺',
      date: 'March 6-8, 2026',
      completed: true,
      sprint: false,
      winner: { driver: 'George Russell', team: 'Mercedes', time: '1:23:06.801' },
      podium: [
        { pos: 1, driver: 'George Russell', team: 'Mercedes' },
        { pos: 2, driver: 'Kimi Antonelli', team: 'Mercedes', gap: '+2.974s' },
        { pos: 3, driver: 'Charles Leclerc', team: 'Ferrari', gap: '+15.519s' },
      ],
      fastestLap: { driver: 'George Russell', team: 'Mercedes', time: '1:20.235' },
    },
    {
      round: 2,
      name: 'Chinese Grand Prix',
      circuit: 'Shanghai International Circuit',
      country: 'China',
      flag: '🇨🇳',
      date: 'March 13-15, 2026',
      completed: true,
      sprint: true,
      winner: { driver: 'Kimi Antonelli', team: 'Mercedes', time: '1:33:15.607' },
      podium: [
        { pos: 1, driver: 'Kimi Antonelli', team: 'Mercedes' },
        { pos: 2, driver: 'George Russell', team: 'Mercedes', gap: '+5.515s' },
        { pos: 3, driver: 'Lewis Hamilton', team: 'Ferrari', gap: '+25.267s' },
      ],
      fastestLap: { driver: 'Kimi Antonelli', team: 'Mercedes', time: '1:35.02' },
    },
    {
      round: 3,
      name: 'Japanese Grand Prix',
      circuit: 'Suzuka Circuit',
      country: 'Japan',
      flag: '🇯🇵',
      date: 'March 27-29, 2026',
      completed: false,
      sprint: false,
    },
    {
      round: 4,
      name: 'Miami Grand Prix',
      circuit: 'Miami International Autodrome',
      country: 'USA',
      flag: '🇺🇸',
      date: 'May 1-3, 2026',
      completed: false,
      sprint: true,
    },
    {
      round: 5,
      name: 'Canadian Grand Prix',
      circuit: 'Circuit Gilles Villeneuve',
      country: 'Canada',
      flag: '🇨🇦',
      date: 'May 22-24, 2026',
      completed: false,
      sprint: true,
    },
    {
      round: 6,
      name: 'Monaco Grand Prix',
      circuit: 'Circuit de Monaco',
      country: 'Monaco',
      flag: '🇲🇨',
      date: 'June 5-7, 2026',
      completed: false,
      sprint: false,
    },
    {
      round: 7,
      name: 'Barcelona-Catalunya Grand Prix',
      circuit: 'Circuit de Barcelona-Catalunya',
      country: 'Spain',
      flag: '🇪🇸',
      date: 'June 12-14, 2026',
      completed: false,
      sprint: false,
    },
    {
      round: 8,
      name: 'Austrian Grand Prix',
      circuit: 'Red Bull Ring',
      country: 'Austria',
      flag: '🇦🇹',
      date: 'June 26-28, 2026',
      completed: false,
      sprint: false,
    },
    {
      round: 9,
      name: 'British Grand Prix',
      circuit: 'Silverstone Circuit',
      country: 'UK',
      flag: '🇬🇧',
      date: 'July 3-5, 2026',
      completed: false,
      sprint: true,
    },
    {
      round: 10,
      name: 'Belgian Grand Prix',
      circuit: 'Circuit de Spa-Francorchamps',
      country: 'Belgium',
      flag: '🇧🇪',
      date: 'July 17-19, 2026',
      completed: false,
      sprint: false,
    },
    {
      round: 11,
      name: 'Hungarian Grand Prix',
      circuit: 'Hungaroring',
      country: 'Hungary',
      flag: '🇭🇺',
      date: 'July 24-26, 2026',
      completed: false,
      sprint: false,
    },
    {
      round: 12,
      name: 'Dutch Grand Prix',
      circuit: 'Circuit Zandvoort',
      country: 'Netherlands',
      flag: '🇳🇱',
      date: 'August 21-23, 2026',
      completed: false,
      sprint: true,
    },
    {
      round: 13,
      name: 'Italian Grand Prix',
      circuit: 'Autodromo Nazionale Monza',
      country: 'Italy',
      flag: '🇮🇹',
      date: 'September 4-6, 2026',
      completed: false,
      sprint: false,
    },
    {
      round: 14,
      name: 'Spanish Grand Prix',
      circuit: 'Madrid Street Circuit',
      country: 'Spain',
      flag: '🇪🇸',
      date: 'September 11-13, 2026',
      completed: false,
      sprint: false,
    },
    {
      round: 15,
      name: 'Azerbaijan Grand Prix',
      circuit: 'Baku City Circuit',
      country: 'Azerbaijan',
      flag: '🇦🇿',
      date: 'September 24-26, 2026',
      completed: false,
      sprint: false,
    },
    {
      round: 16,
      name: 'Singapore Grand Prix',
      circuit: 'Marina Bay Street Circuit',
      country: 'Singapore',
      flag: '🇸🇬',
      date: 'October 9-11, 2026',
      completed: false,
      sprint: true,
    },
    {
      round: 17,
      name: 'United States Grand Prix',
      circuit: 'Circuit of the Americas',
      country: 'USA',
      flag: '🇺🇸',
      date: 'October 2026',
      completed: false,
      sprint: false,
    },
    {
      round: 18,
      name: 'Mexico City Grand Prix',
      circuit: 'Autodromo Hermanos Rodriguez',
      country: 'Mexico',
      flag: '🇲🇽',
      date: 'October 2026',
      completed: false,
      sprint: false,
    },
    {
      round: 19,
      name: 'Brazilian Grand Prix',
      circuit: 'Autodromo Jose Carlos Pace',
      country: 'Brazil',
      flag: '🇧🇷',
      date: 'November 2026',
      completed: false,
      sprint: false,
    },
    {
      round: 20,
      name: 'Las Vegas Grand Prix',
      circuit: 'Las Vegas Strip Circuit',
      country: 'USA',
      flag: '🇺🇸',
      date: 'November 2026',
      completed: false,
      sprint: false,
    },
    {
      round: 21,
      name: 'Qatar Grand Prix',
      circuit: 'Lusail International Circuit',
      country: 'Qatar',
      flag: '🇶🇦',
      date: 'November 2026',
      completed: false,
      sprint: false,
    },
    {
      round: 22,
      name: 'Abu Dhabi Grand Prix',
      circuit: 'Yas Marina Circuit',
      country: 'UAE',
      flag: '🇦🇪',
      date: 'December 4-6, 2026',
      completed: false,
      sprint: false,
    },
  ],
  drivers: [
    { number: 1, name: 'Lando Norris', team: 'McLaren', nationality: '🇬🇧' },
    { number: 4, name: 'Oscar Piastri', team: 'McLaren', nationality: '🇦🇺' },
    { number: 3, name: 'Max Verstappen', team: 'Red Bull', nationality: '🇳🇱' },
    { number: 6, name: 'Isack Hadjar', team: 'Red Bull', nationality: '🇫🇷' },
    { number: 63, name: 'George Russell', team: 'Mercedes', nationality: '🇬🇧' },
    { number: 12, name: 'Kimi Antonelli', team: 'Mercedes', nationality: '🇮🇹' },
    { number: 44, name: 'Lewis Hamilton', team: 'Ferrari', nationality: '🇬🇧' },
    { number: 16, name: 'Charles Leclerc', team: 'Ferrari', nationality: '🇲🇨' },
    { number: 14, name: 'Fernando Alonso', team: 'Aston Martin', nationality: '🇪🇸' },
    { number: 18, name: 'Lance Stroll', team: 'Aston Martin', nationality: '🇨🇦' },
    { number: 55, name: 'Carlos Sainz', team: 'Williams', nationality: '🇪🇸' },
    { number: 23, name: 'Alexander Albon', team: 'Williams', nationality: '🇹🇭' },
    { number: 10, name: 'Pierre Gasly', team: 'Alpine', nationality: '🇫🇷' },
    { number: 43, name: 'Franco Colapinto', team: 'Alpine', nationality: '🇦🇷' },
    { number: 87, name: 'Oliver Bearman', team: 'Haas', nationality: '🇬🇧' },
    { number: 31, name: 'Esteban Ocon', team: 'Haas', nationality: '🇫🇷' },
    { number: 27, name: 'Nico Hulkenberg', team: 'Audi', nationality: '🇩🇪' },
    { number: 5, name: 'Gabriel Bortoleto', team: 'Audi', nationality: '🇧🇷' },
    { number: 30, name: 'Liam Lawson', team: 'Racing Bulls', nationality: '🇳🇿' },
    { number: 41, name: 'Arvid Lindblad', team: 'Racing Bulls', nationality: '🇬🇧' },
    { number: 77, name: 'Valtteri Bottas', team: 'Cadillac', nationality: '🇫🇮' },
    { number: 11, name: 'Sergio Perez', team: 'Cadillac', nationality: '🇲🇽' },
  ],
  championship: {
    drivers: [
      { pos: 1, driver: 'Kimi Antonelli', team: 'Mercedes', points: 44 },
      { pos: 2, driver: 'George Russell', team: 'Mercedes', points: 43 },
      { pos: 3, driver: 'Charles Leclerc', team: 'Ferrari', points: 15 },
      { pos: 4, driver: 'Lewis Hamilton', team: 'Ferrari', points: 15 },
      { pos: 5, driver: 'Lando Norris', team: 'McLaren', points: 10 },
    ],
    constructors: [
      { pos: 1, team: 'Mercedes', points: 87 },
      { pos: 2, team: 'Ferrari', points: 30 },
      { pos: 3, team: 'McLaren', points: 10 },
    ],
  },
} as const

// Helper: get completed races only
export const completedRaces = SEASON_2026.races.filter(r => r.completed)

// Helper: get latest race (most recent completed)
export const latestRace = completedRaces[completedRaces.length - 1]

// Helper: get latest fastest lap across all completed races
export const latestFastestLap = latestRace?.fastestLap

// Helper: championship leader
export const championshipLeader = SEASON_2026.championship.drivers[0]
